name: Deploy to firebase functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci --prefer-offline
      - run: npm i -g firebase-tools

      - run: npm run build
      - run: firebase deploy --non-interactive --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_PROJECT }}" --only functions -f
